# Generated by Django 5.0 on 2023-12-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description_short', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('description_long', models.TextField(blank=True, verbose_name='Расширенное описание')),
                ('lng', models.FloatField(blank=True, verbose_name='Долгота')),
                ('lat', models.FloatField(blank=True, verbose_name='Широта')),
            ],
        ),
    ]
